"""add identity to primary keys

Revision ID: 20260621_0205
Revises: 353dcb863728
Create Date: 2026-06-21 02:05:00.000000
"""

from collections.abc import Sequence

from alembic import op

revision: str = "20260621_0205"
down_revision: str | None = "353dcb863728"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        DO $$
        DECLARE
            current_table_name text;
            next_id bigint;
            id_is_identity text;
            id_default text;
        BEGIN
            FOREACH current_table_name IN ARRAY ARRAY[
                'users',
                'genres',
                'languages',
                'countries',
                'songs',
                'opinions'
            ]
            LOOP
                SELECT is_identity, column_default
                INTO id_is_identity, id_default
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = current_table_name
                  AND column_name = 'id';

                IF id_is_identity = 'NO' AND id_default IS NULL THEN
                    EXECUTE format(
                        'ALTER TABLE %I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY',
                        current_table_name
                    );
                    EXECUTE format('SELECT COALESCE(MAX(id), 0) + 1 FROM %I', current_table_name)
                    INTO next_id;
                    EXECUTE format(
                        'ALTER TABLE %I ALTER COLUMN id RESTART WITH %s',
                        current_table_name,
                        next_id
                    );
                END IF;
            END LOOP;
        END
        $$;
        """
    )


def downgrade() -> None:
    op.execute(
        """
        DO $$
        DECLARE
            current_table_name text;
        BEGIN
            FOREACH current_table_name IN ARRAY ARRAY[
                'users',
                'genres',
                'languages',
                'countries',
                'songs',
                'opinions'
            ]
            LOOP
                IF EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = 'public'
                      AND table_name = current_table_name
                      AND column_name = 'id'
                      AND is_identity = 'YES'
                ) THEN
                    EXECUTE format(
                        'ALTER TABLE %I ALTER COLUMN id DROP IDENTITY IF EXISTS',
                        current_table_name
                    );
                END IF;
            END LOOP;
        END
        $$;
        """
    )
