"""Added url in Songs table

Revision ID: 353dcb863728
Revises: 9f8ca90e218f
Create Date: 2026-06-21 16:43:06.347451
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '353dcb863728'
down_revision: str | None = '9f8ca90e218f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'url')
    # ### end Alembic commands ###

