"""country event relationship

Revision ID: d18090a6c68a
Revises: 20260812_2000
Create Date: 2026-08-12 20:45:36.015806
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd18090a6c68a'
down_revision: str | None = '20260812_2000'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('host_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_events_host_id'), 'events', ['host_id'], unique=False)
    op.create_foreign_key(op.f('fk_events_host_id_countries'), 'events', 'countries', ['host_id'], ['id'], ondelete='CASCADE')
    op.drop_column('events', 'host')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('host', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_events_host_id_countries'), 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_host_id'), table_name='events')
    op.drop_column('events', 'host_id')
    # ### end Alembic commands ###

