DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'stage') THEN
        CREATE TYPE stage AS ENUM ('FIRST', 'FINAL');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'vocal') THEN
        CREATE TYPE vocal AS ENUM ('male', 'female', 'mix');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT true NOT NULL,
    is_admin BOOLEAN DEFAULT false NOT NULL,
    token_version INTEGER DEFAULT 0 NOT NULL,
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_users_username ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email);

CREATE TABLE IF NOT EXISTS genres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_genres PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_genres_name ON genres (name);

CREATE TABLE IF NOT EXISTS languages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_languages PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_languages_name ON languages (name);

CREATE TABLE IF NOT EXISTS countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    CONSTRAINT pk_countries PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_countries_name ON countries (name);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL,
    year INTEGER NOT NULL,
    host VARCHAR(255) NOT NULL,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ix_events_year ON events (year);

CREATE TABLE IF NOT EXISTS songs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    country_id BIGINT NOT NULL,
    event_id BIGINT,
    year INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    artist VARCHAR(255) NOT NULL,
    bpm INTEGER,
    key VARCHAR(16),
    vocal vocal NOT NULL,
    energy INTEGER,
    danceability INTEGER,
    happiness INTEGER,
    CONSTRAINT pk_songs PRIMARY KEY (id),
    CONSTRAINT fk_songs_country_id_countries FOREIGN KEY (country_id) REFERENCES countries (id) ON DELETE CASCADE,
    CONSTRAINT fk_songs_event_id_events FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE SET NULL,
    CONSTRAINT ck_songs_energy_range CHECK (energy BETWEEN 0 AND 100),
    CONSTRAINT ck_songs_danceability_range CHECK (danceability BETWEEN 0 AND 100),
    CONSTRAINT ck_songs_happiness_range CHECK (happiness BETWEEN 0 AND 100)
);

CREATE INDEX IF NOT EXISTS ix_songs_country_id ON songs (country_id);
CREATE INDEX IF NOT EXISTS ix_songs_event_id ON songs (event_id);
CREATE INDEX IF NOT EXISTS ix_songs_year ON songs (year);

CREATE TABLE IF NOT EXISTS opinions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    song_id BIGINT NOT NULL,
    score INTEGER NOT NULL,
    note TEXT,
    stage stage NOT NULL,
    CONSTRAINT pk_opinions PRIMARY KEY (id),
    CONSTRAINT ck_opinions_score_allowed CHECK (score IN (0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 12)),
    CONSTRAINT fk_opinions_user_id_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_opinions_song_id_songs FOREIGN KEY (song_id) REFERENCES songs (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_opinions_user_id ON opinions (user_id);
CREATE INDEX IF NOT EXISTS ix_opinions_song_id ON opinions (song_id);

CREATE TABLE IF NOT EXISTS song_genres (
    song_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    CONSTRAINT pk_song_genres PRIMARY KEY (song_id, genre_id),
    CONSTRAINT fk_song_genres_song_id_songs FOREIGN KEY (song_id) REFERENCES songs (id) ON DELETE CASCADE,
    CONSTRAINT fk_song_genres_genre_id_genres FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS song_languages (
    song_id BIGINT NOT NULL,
    language_id BIGINT NOT NULL,
    CONSTRAINT pk_song_languages PRIMARY KEY (song_id, language_id),
    CONSTRAINT fk_song_languages_song_id_songs FOREIGN KEY (song_id) REFERENCES songs (id) ON DELETE CASCADE,
    CONSTRAINT fk_song_languages_language_id_languages FOREIGN KEY (language_id) REFERENCES languages (id) ON DELETE CASCADE
);
