import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { api } from '../api/client'
import type { AdminData, CatalogItem, FormValues } from '../types'
import { SongForm } from './SongForm'

type Tab = 'songs' | 'events' | 'users' | 'countries' | 'genres' | 'languages'
const Field = ({ label, children }: { label: string; children: ReactNode }) => <label>{label}{children}</label>
function Select({ value, onChange, options, blank = false, multiple = false }: { value: string | number | readonly string[] | undefined | null; onChange: (value: string | string[]) => void; options: Array<CatalogItem | string>; blank?: boolean; multiple?: boolean }) { return <select value={value ?? (multiple ? [] : '')} multiple={multiple} onChange={event => onChange(multiple ? [...event.target.selectedOptions].map(option => option.value) : event.target.value)}>{blank && <option value="">—</option>}{options.map(option => <option key={typeof option === 'string' ? option : option.id} value={typeof option === 'string' ? option : option.id}>{typeof option === 'string' ? option : option.name}</option>)}</select> }
function Editor({ initial, render, submit }: { initial: FormValues; render: (value: FormValues, set: (key: string, item: FormValues[string]) => void) => ReactNode; submit: (value: FormValues) => void }) { const [value, setValue] = useState<FormValues>(initial); return <form className="editor" onSubmit={event => { event.preventDefault(); submit(value); setValue(initial) }}>{render(value, (key, item) => setValue({ ...value, [key]: item }))}<button>Добавить</button></form> }

export function Admin({ onBack, onEditSong }: { onBack: () => void; onEditSong: (songId: number) => void }) {
  const [data, setData] = useState<AdminData | null>(null), [tab, setTab] = useState<Tab>('songs'), [notice, setNotice] = useState('')
  const load = () => void api.admin().then(result => { if (result) setData(result) }).catch(error => setNotice((error as Error).message)); useEffect(load, [])
  async function action(url: string, values: FormValues, question?: string) { if (question && !window.confirm(question)) return; try { await api.adminAction(url, values); const result = await api.adminMessage(); const message = result?.message; setNotice(message?.text ?? 'Сохранено'); if (message?.kind !== 'error') load() } catch (error) { setNotice((error as Error).message) } }
  if (!data) return <main className="container">Загрузка… {notice && <p className="error">{notice}</p>}</main>
  const Catalog = ({ type, title }: { type: 'countries' | 'genres' | 'languages'; title: string }) => <section><h2>{title}</h2><form className="inline" onSubmit={(event: FormEvent<HTMLFormElement>) => { event.preventDefault(); void action(type === 'countries' ? '/admin/countries' : `/admin/catalog/${type}`, { name: new FormData(event.currentTarget).get('name') as string }); event.currentTarget.reset() }}><input name="name" placeholder="Название" required /><button>Добавить</button></form><table><tbody>{data[type].map(item => <tr key={item.id}><td><input defaultValue={item.name} onBlur={event => void action(`/admin/${type}/${item.id}/update`, { name: event.target.value })} /></td><td><button className="danger" onClick={() => void action(`/admin/${type}/${item.id}/delete`, {}, 'Удалить запись?')}>Удалить</button></td></tr>)}</tbody></table></section>
  return <main className="container wide"><header><h1>Администрирование</h1><button className="secondary" onClick={onBack}>К оценкам</button></header>{notice && <p className={notice === 'Сохранено' ? 'notice' : 'error'}>{notice}</p>}<nav className="tabs">{([['songs','Песни'],['events','Мероприятия'],['users','Пользователи'],['countries','Страны'],['genres','Жанры'],['languages','Языки']] as [Tab, string][]).map(([id, title]) => <button key={id} onClick={() => setTab(id)} className={tab === id ? 'active' : ''}>{title}</button>)}</nav>{tab === 'countries' && <Catalog type="countries" title="Страны" />}{tab === 'genres' && <Catalog type="genres" title="Жанры" />}{tab === 'languages' && <Catalog type="languages" title="Языки" />}{tab === 'events' && <Events data={data} action={action} />}{tab === 'users' && <Users data={data} action={action} />}{tab === 'songs' && <Songs data={data} action={action} onEditSong={onEditSong} />}</main>
}

function Events({ data, action }: { data: AdminData; action: (url: string, values: FormValues, question?: string) => void }) { const blank = { name: '', year: new Date().getFullYear(), host_id: data.countries[0]?.id }; return <section><h2>Мероприятия</h2><Editor initial={blank} submit={value => action('/admin/events', value)} render={(value,set) => <><Field label="Название"><input value={String(value.name)} onChange={event => set('name', event.target.value)} /></Field><Field label="Год"><input type="number" value={Number(value.year)} onChange={event => set('year', event.target.value)} /></Field><Field label="Хозяин"><Select value={value.host_id as number} onChange={item => set('host_id', item)} options={data.countries} /></Field></>} /><table><thead><tr><th>Название</th><th>Год</th><th>Хозяин</th><th>Настройки</th><th /></tr></thead><tbody>{data.events.map(item => <tr key={item.id}><td><input defaultValue={item.name} onBlur={event => action(`/admin/events/${item.id}/update`, { ...item, name: event.target.value })} /></td><td><input type="number" defaultValue={item.year} onBlur={event => action(`/admin/events/${item.id}/update`, { ...item, year: event.target.value })} /></td><td><Select value={item.host_id} onChange={value => action(`/admin/events/${item.id}/update`, { ...item, host_id: value })} options={data.countries} /></td><td>{([['is_current','Текущее'],['first_stage_open','Первый этап'],['final_stage_open','Финал']] as const).map(([key,label]) => <label key={key}><input type="checkbox" defaultChecked={item[key]} onChange={event => action(`/admin/events/${item.id}/settings`, { is_current: key === 'is_current' ? event.target.checked : item.is_current, first_stage_open: key === 'first_stage_open' ? event.target.checked : item.first_stage_open, final_stage_open: key === 'final_stage_open' ? event.target.checked : item.final_stage_open })} />{label}</label>)}</td><td><button className="danger" onClick={() => action(`/admin/events/${item.id}/delete`, {}, 'Удалить мероприятие?')}>Удалить</button></td></tr>)}</tbody></table></section> }
function Users({ data, action }: { data: AdminData; action: (url: string, values: FormValues, question?: string) => void }) { return <section><h2>Пользователи</h2><Editor initial={{ username: '', email: '', password: '', is_admin: false }} submit={value => action('/admin/users', value)} render={(value,set) => <><Field label="Логин"><input value={String(value.username)} onChange={event => set('username', event.target.value)} /></Field><Field label="Почта"><input type="email" value={String(value.email)} onChange={event => set('email', event.target.value)} /></Field><Field label="Пароль"><input type="password" value={String(value.password)} onChange={event => set('password', event.target.value)} /></Field><Field label="Администратор"><input type="checkbox" checked={Boolean(value.is_admin)} onChange={event => set('is_admin', event.target.checked)} /></Field></>} /><table><thead><tr><th>Логин</th><th>Почта</th><th>Админ</th><th>Активен</th><th /></tr></thead><tbody>{data.users.map(item => <tr key={item.id}><td><input defaultValue={item.username} onBlur={event => action(`/admin/users/${item.id}/update`, { ...item, username: event.target.value })} /></td><td>{item.email}</td><td><input type="checkbox" defaultChecked={item.is_admin} onChange={event => action(`/admin/users/${item.id}/update`, { ...item, is_admin: event.target.checked })} /></td><td><input type="checkbox" defaultChecked={item.is_active} onChange={event => action(`/admin/users/${item.id}/update`, { ...item, is_active: event.target.checked })} /></td><td><button className="danger" onClick={() => action(`/admin/users/${item.id}/delete`, {}, 'Удалить пользователя?')}>Удалить</button></td></tr>)}</tbody></table></section> }
function Songs({ data, action, onEditSong }: { data: AdminData; action: (url: string, values: FormValues, question?: string) => void; onEditSong: (songId: number) => void }) { const blank: FormValues = { name:'',artist:'',year:new Date().getFullYear(),vocal:data.vocals[0],country_id:data.countries[0]?.id,event_id:'',bpm:'',key:'',energy:'',danceability:'',happiness:'',url:'',genre_ids:[],language_ids:[] }; return <section><h2>Песни</h2><SongForm initial={blank} data={data} submitLabel="Добавить песню" onSubmit={value => action('/admin/songs', value)} /><div className="table"><table><thead><tr><th>Песня</th><th>Год / вокал</th><th>Страна / мероприятие</th><th>Характеристики</th><th /></tr></thead><tbody>{data.songs.map(song => <tr key={song.id}><td><b>{song.name}</b><br />{song.artist}</td><td>{song.year}<br />{song.vocal}</td><td>{song.country}<br />{song.event || '—'}</td><td>BPM: {song.bpm ?? '—'} · Энергия: {song.energy ?? '—'} · Танцы: {song.danceability ?? '—'} · Позитив: {song.happiness ?? '—'}</td><td className="song-actions"><button onClick={() => onEditSong(song.id)}>Редактировать</button><button className="danger" onClick={() => action(`/admin/songs/${song.id}/delete`, {}, 'Удалить песню?')}>Удалить</button></td></tr>)}</tbody></table></div></section> }
